# Generated by Django 2.2.6 on 2019-12-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fphoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(upload_to='')),
                ('img_2', models.ImageField(upload_to='')),
                ('num_evd', models.FloatField(null=True)),
            ],
        ),
    ]
