# Generated by Django 2.2.6 on 2019-10-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_auto_20191019_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='evklid',
            field=models.FloatField(default=0.7),
            preserve_default=False,
        ),
    ]
