# Generated by Django 2.2.6 on 2019-10-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_photo_evklid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='evklid',
            field=models.FloatField(null=True),
        ),
    ]
