# Generated by Django 2.2.6 on 2019-10-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_auto_20191019_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='num_evd',
            field=models.FloatField(null=True),
        ),
    ]
